name: Test Automation

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read

env:
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_END_USER: ${{ secrets.MAIL_END_USER }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Generate Tests Reports
        id: generate_report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results - ${{ github.run_number }}
          path: test-results/junit.xml
          reporter: java-junit
          fail-on-error: false

      - name: Publish Results to Summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_run: false
          files: |
            test-results/junit.xml

      - name: Send Email
        uses: dawidd6/action-send-mail@v3.11.0
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ env.MAIL_USERNAME }}
          password: ${{ env.MAIL_PASSWORD }}
          from: ${{ env.MAIL_USERNAME }}
          to: ${{ env.MAIL_END_USER }}
          subject: React Todo App - Test Results (${{ job.status }})
          body: |
            Test automation results for React Todo App

            Status: ${{ job.status }}
            Workflow: ${{ github.workflow }}
            Run: #${{ github.run_number }}

            View detailed results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
